USE inventarioUG;

INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Niguna', 'Ninguna ');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Computadora', 'Toda clase de computadoras');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Impresora', '"Tipos de impresoras: tinta');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Dron', '"Drones programables');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Smartphone', 'Smartphones y Tablets');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Smartwatch', 'Relojes inteligentes');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Smartpen ', 'Lápices inteligentes');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Pantalla o monitor', 'Pantallas o monitores para computadoras');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Mesa táctil  ', 'Pantalla táctil de grandes dimensiones');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Teclado ', 'Teclado para cualquier tipo de computadora');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Mouse ', 'Mouse para cualquier tipo de computadora');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Telefono ', 'Teléfonos alámbricos o inalámbricos de oficina');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Cámara ', '"Cámara profesional');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Sillón ', 'Sillón para sala o recepción');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Escritorio ', 'Escritorio de trabajo para oficina');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Archivero ', 'Todo tipo de archiveros');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Estante ', 'Todo tipo de estantes');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Pizarrón ', 'Todo tipo de pizarrones');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Librero ', 'Librero de cualquier tamaño y material');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Mesa', 'Cualquier tipo de mesa para comedor o cafetería');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Silla', 'Cualquier tipo de silla');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Banco ', 'Cualquier tipo de banco');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Unidad Almacenamiento ', '"Unidades tipo SSD');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Seguidor de ojos ', 'Dispositivo desarrollado para seguir los ojos');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Audifonos ', 'Cualquier tipo de audífonos');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Anaquel ', 'Cualquier tipo de anaquel');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Kit diagnostico', 'Kit de diagnóstico para equipos de eletrónica');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Fotocopiadora', 'Impresora para copiar e imprimir');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Proyector ', 'Proyector de cualquier tipo');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Pantalla multitouch ', 'Pantalla touch para conectar a una computadora');
