USE inventarioUG;

INSERT INTO puesto(nombre, descripcion, fecha) VALUES('Profesor de tiempo completo (PTC)', 'Profesor con contrato de tiempo completo encargado de investigación, docencia, vinculación, etc', '2015-01-25');
INSERT INTO campus(nombre) VALUES('Irapuato-Salamanca');
INSERT INTO sede(id_campus, nombre) VALUES(1, 'Yuriria');
INSERT INTO entidad(id_sede, nombre) VALUES(1, 'DEM Yuriria');
INSERT INTO empleado(id_puesto, id_entidad, nombre, ape_paterno, ape_materno, fecha_registro) VALUES(1, 1, 'Geovani', 'Hernández', 'Gómez', '2015-01-08');
INSERT INTO categoria(nombre, descripcion) VALUES('Muebles', 'Escritorios, mesas, sillas, bancos, sillones');
INSERT INTO categoria(nombre, descripcion) VALUES('Electrónica', 'Computadoras, Cables, Impresoras, Monitores, pantallas, drones');
INSERT INTO categoria(nombre, descripcion) VALUES('Deportes', 'Balones, conos, caminadora, red de portería');
INSERT INTO categoria(nombre, descripcion) VALUES('Electrodomesticos', 'Horno micro-ondas, refrijerador, estufa');
INSERT INTO categoria(nombre, descripcion) VALUES('Vehículos', 'Carros, motos, lanchas, vicicletas');
INSERT INTO categoria(nombre, descripcion) VALUES('Herramientas', 'Palas, martillos, taladros, desarmadores');

INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Computadora', 'Toda clase de computadora');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Impresora', 'Tipos de impresora: tinta, láse o 3D');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Dron', '"Drones programables');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Smartphone', 'Smartphones y Tablets');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Smartwatch', 'Relojes inteligentes');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Smartpen ', 'Lápices inteligentes');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Pantalla o monitor', 'Pantallas o monitores para computadoras');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Mesa táctil  ', 'Pantalla táctil de grandes dimensiones');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Teclado ', 'Teclado para cualquier tipo de computadora');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Mouse ', 'Mouse para cualquier tipo de computadora');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Telefono ', 'Teléfonos alámbricos o inalámbricos de oficina');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Cámara ', '"Cámara profesional');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Sillón ', 'Sillón para sala o recepción');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Escritorio ', 'Escritorio de trabajo para oficina');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Archivero ', 'Todo tipo de archiveros');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Estante ', 'Todo tipo de estantes');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Pizarrón ', 'Todo tipo de pizarrones');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Librero ', 'Librero de cualquier tamaño y material');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Mesa', 'Cualquier tipo de mesa para comedor o cafetería');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Silla', 'Cualquier tipo de silla');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Banco ', 'Cualquier tipo de banco');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Unidad Almacenamiento ', '"Unidades tipo SSD');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Seguidor de ojos ', 'Dispositivo desarrollado para seguir los ojos');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Audifonos ', 'Cualquier tipo de audífonos');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(1, 'Anaquel ', 'Cualquier tipo de anaquel');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(3, 'Kit diagnostico', 'Kit de diagnóstico para equipos de eletrónica');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Fotocopiadora', 'Impresora para copiar e imprimir');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Proyector ', 'Proyector de cualquier tipo');
INSERT INTO sub_categoria(id_categoria, nombre, descripcion) VALUES(2, 'Pantalla multitouch ', 'Pantalla touch para conectar a una computadora');

INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(1, 'Desktop', 'Computadora de escritorio convencional con CPU');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(1, 'Laptop', 'Computadora portatil en las categorias: laptop y ultrabook');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(1, 'Servidor', 'Computadora especializada para el alto rendimiento');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(1, 'Mini-PC', '"Computadora de formato pequeño tipo: Raspberry PI');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(1, 'All-In-One', 'Computadora en la cual el CPU está embebido en un case junto al monitor');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(2, 'Impresora 3D ', 'Impresora encargada de imprimir objetos en tercera dimensión');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(2, 'Impresora laser', 'Impresora con tecnologia láser para imprimir');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(2, 'Multifuncional ', '"Impresora con tecnología de titna o láser capaz de imprimir');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(2, 'Telefono IP ', 'Teléfono configurable con una red interna al cual se le asigna una dirección IP');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(2, 'Telefono convencional', 'Teléfono alámbrico o inalámbrico para casa u oficina');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(12, 'Cámara fotografica', 'Dispositivo fabricado únicamente para capturar fotografías');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(12, 'Cámara de video ', 'Dispositivo fabricado para grabar videos');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(12, 'Cámara multifuncional ', 'Dispositivo fabricado para capturar fotografías y videos');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(7, 'Pantalla LED', 'Pantallas o monitores con tecnología LED en su matriz ');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(7, 'Pantalla LCD', 'Pantallas o monitos con tecnología LCD');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(7, 'Pantalla Plasma', 'Pantallas  o monitores con tecnología Plasma');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(3, 'Dron programable ', 'Dron programable para tareas en específico');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(3, 'Dron modular ', 'Dron con la capacidad de intercambiar sus partes de manera sencilla ');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(22, 'Unidad de estado sólido', 'Dispositivo de almacenamiento de datos de memoria flash');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(22, 'Disco duro ', 'Dispotivios de almacenamiento de datos mediante discos magnéticos');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(22, 'Memoria USB ', 'Dispositivo de almacenamiento con tecnología Flash en formato USB');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(22, 'Micro SD', 'Dispositivo de almacenamiento con tecnología Flash en formato MicroSD');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(13, 'Sillón ejecutivo ', 'Sillón tipo ejecutivo');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(13, 'Sillón taburete ', 'Sillón tipo taburete');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(13, 'Sillón rinconero ', 'Sillón tipo rinconero');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(13, 'Sillón modular ', 'Sillón modular compuesto de diferentes piezas');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(14, 'Escritorio de madera ', 'Escritorio construido con madera');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(14, 'Escritorio de metal ', 'Escritorio con estructura de metal');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(14, 'Escritorio ejecutivo ', 'Escrotiro tipo ejecutivo');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(15, 'Archivero de madera', 'Archivero construido completamente de madera');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(15, 'Archivero de metal ', 'Archivero construido completamente de metal');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(15, 'Archivero escolar ', 'Archivero tipo escolar');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(16, 'Estante de madera', 'Estante construido completamente con madera');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(16, 'Estante de metal ', 'Estante construido completamente con madera');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(17, 'Pizarrón blanco ', 'Pizarrón blanco para salón de clases');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(17, 'Pizarrón cuadriculado', 'Pizarrón blanco con cuadricula guía');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(17, 'Pizarrón de cristal ', 'Pizarrón transparente hecho de vidrio');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(18, 'Librero bajo ', 'Librero de tamaño reducido');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(18, 'Librero modular ', 'Librero constituido de varias partes separables e intercambiables');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(18, 'Librero empotrado ', 'Librero asegurado o empotrado a la pared');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(19, 'Mesa redonda ', 'Mesa con forma redonda');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(19, 'Mesa de madera ', 'Mesa construida con madera');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(19, 'Mesa de metal ', 'Mesa construida con metal');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(19, 'Mesa de plastico ', 'Mesa construida con plástico');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(21, 'Banco de metal ', 'Banco construido con metal');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(21, 'Banco de madera ', 'Banco construido con madera');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(21, 'Banco de plastico ', 'Banco construido de plástico');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(20, 'Silla metalica ', 'Silla construida con metal');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(20, 'Silla de madera ', 'Silla construida con madera');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(20, 'Silla ejecutiva ', 'Silla tipo ejecutivo');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(20, 'Silla de plastico ', 'Silla construida con plástico');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(20, 'Silla secretarial ', 'Silla tipo secretarial');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(25, 'Anaquel de madera', 'Anaquel construido mayormente con madera');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(25, 'Anaquel de metal', 'Anaquel construido mayormente metal');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(24, 'Diadema ', 'Diadema para audífonos');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(24, 'Audifonos inalambricos ', 'Audífonos de tipo inalámbricos con tecnología Bluetooth o WiFi para la transmisión de datos');
INSERT INTO sub_division(id_subcategoria, nombre, descripcion) VALUES(24, 'Auriculares ', 'Audífonos de tipo alámbricos con jack de 3.5mm');

SELECT * FROM sub_division;

